### ISSUE TITLE
[Bug] Weird Behaviour with "modid" and "name" of products

### ISSUE THREAD

**Issue by creeloper27** [Allymonies/Radon#14]
If I use the following values:
![image](https://github.com/Allymonies/Radon/assets/20074177/272bffe0-a5e4-4202-908a-e805328f9bcb)
when using `/pay ky37t6kqc3 1 drive` it succesfully dispenses tho gives the error: 
![image](https://github.com/Allymonies/Radon/assets/20074177/4d3ca2c0-3919-4562-a9be-7a4a9ea230f3)

Also on the same note, what exactly do you need to put in these 2 fields?
putting `computercraft` in `modid` and `disk_drive` in `name` does not seem to work (same error), tho putting `computercraft:disk_drive` in `modid` and `computercraft:disk_drive` in `name` seem to work fine, what is going on here?

**Comment by Allymonies** [comment]
`modid` should be the id of the item, so what you have in the screenshot looks correct. `name` is used to display the item in the products list. The `address` field is used to determine what meta must be used to purchase the product, so in order to have `/pay ky37t6kqc3 1 drive` to work, `address` must be set to `drive`.

**Comment by creeloper27** [comment]
Thanks for clarifying the meaning of the values!

It turns out that error was not coming from the shop I was testing but instead anotherone I had setup for testing temporarly at another location 😅 so there are no bugs luckly, just me beeing silly.
